version: 2.1
jobs:
  build:
    parallelism: 30
    machine:
      image: ubuntu-2204:2022.04.1
    steps:
      - checkout
      - run: |
          sudo apt-get update -y
          sudo apt-get install npm -y
          sudo apt-get install nodejs -y